export const projectsList = [
  {
    color: "bg-project-0",
    name: "Fix Machines",
    date: "april 2024",
    image: "/projects/project-3-next-14-Fix-Machines.png",
    description:
      "this web site base on the idea of someone how work fix machines can be used to track the repairing process",
    github: "https://github.com/dany679/Fix-Machines-Next-14",
    link: "https://fix-machines-next-14.vercel.app/",
    tools: [
      { name: "next-14" },
      { name: "tailwind" },
      { name: "Mui" },
      { name: "React-query-string" },
      { name: "TansStack(react-query)" },
      { name: "react-form-hook" },
      { name: "zod" },
      { name: "Nestjs" },
      { name: "prisma" },
      { name: "Postgresql" },
      { name: "cypress" },
      { name: "react testing library" },
    ],
  },
  {
    name: "Promtopia",
    description:
      "Promtopia is a web app to save and find prompt or tag prompts.",
    image: "/projects/project-1-next-full.png",
    github: "https://github.com/dany679/Next-13-Full-Stack",
    link: "https://next-13-full-stack-seven.vercel.app/",
    date: "ago 2023",
    color: "bg-project-2",
    tools: [
      { name: "next-13" },
      { name: "tailwind" },
      { name: "mongodb" },
      { name: "clerk/jwt" },
    ],
  },

  {
    color: "bg-project-0",
    name: "Genius",
    date: "may 2020",
    description:
      "The project is a website to generate data like 'images, conversation , code 'through the prompt developed using openAi and stripe",
    image: "/projects/project2-ai-saas-genius.png",
    github: "https://github.com/dany679/next13-ai-clerk-prisma-saas-stripe",
    link: "https://next13-ai-clerk-prisma-saas-stripe.vercel.app/",
    tools: [
      { name: "next-13" },
      { name: "tailwind" },
      { name: "prisma" },
      { name: "Mysql" },
      { name: "stripe" },
      { name: "clerk/jwt" },
    ],
  },
];

export const experienceList = [
  {
    startDate: "2021",
    endDate: "2022",
    title: "Inside the box",
    location: "Florianópolis, SC - Brazil",
    image: "/jobs/work-inside.png",
    description:
      "The company make other company's products more accessible to the inside public. the website and app are made to simplify the process of verification, education and support .",
    link: "https://insidethebox.com.br/",
    tools: [
      { name: "React" },
      { name: "React native" },
      { name: "Redux" },
      { name: "Mui" },
      { name: "Ts" },
      { name: "Nodejs" },
      { name: "prisma" },
      { name: "Mysql" },
      { name: "Clickup" },
      { name: "Scrum" },
    ],
  },
  {
    startDate: "2022",
    endDate: "2023",
    title: "Roadr",
    location: "Los Angeles, CA - USA",
    remote: true,
    image: "/jobs/work-inside.png",
    description:
      "The company has a new product that is a car service repair platform. The main goal of the platform that allows the users to find services for car problems in a simple and fast way. the company use B2B and B2C models",
    link: "https://roadr.com/",
    tools: [
      { name: "React" },
      { name: "Redux" },
      { name: "StyledComponents" },
      { name: "Ts" },
      { name: "Nodejs" },
      { name: "mongoDb" },
      { name: "Jira" },
      { name: "Scrum" },
    ],
  },
  {
    startDate: "2023",
    endDate: "2024",
    title: "Furando a fila squad",
    location: "BH, MG - Brazil",
    image: "/jobs/work-inside.png",
    description:
      "The company has a new product that is a car service repair platform. The main goal of the platform that allows the users to find services for car problems in a simple and fast way. the company use B2B and B2C models",
    link: "https://furandoafila.com.br/",
    tools: [
      { name: "Next" },
      { name: "Redux" },
      { name: "Tailwind" },
      { name: "Ts" },
      { name: "Nest" },
      { name: "Postgresql" },
      { name: "Jira" },
      { name: "Scrum" },
    ],
  },
  {
    startDate: "2023",
    // endDate: "2023",
    title: "Freelancer",
    location: "Remote",
    image: "/jobs/work-inside.png",
    description:
      "Generate new website or app, features, fix bugs, and improve the performance of existing code. work with the team to improve the code quality and the architecture of the application. ",
    linkedin: "https://github.com/dany679/Fix-Machines-Next-14",
    tools: [
      { name: "Next" },
      { name: "Redux" },
      { name: "Tailwind" },
      { name: "Mui" },
      { name: "Ts" },
      { name: "Node" },
      { name: "Nest" },
      { name: "Postgresql" },
      { name: "Mysql" },
    ],
  },
];
